#!/bin/bash

env_args=()

for row in $(kubectl get configmap bob-config -o json | jq -c '.data | to_entries[]'); do
  key=$(echo "${row}" | jq -r '.key')
  decoded=$(echo "${row}" | jq -r '.value')
  env_args+=(-e)
  env_args+=("${key}=${decoded}")
done

for row in $(kubectl get secret bob-secret -o json | jq -c '.data | to_entries[]'); do
  key=$(echo "${row}" | jq -r '.key')
  decoded=$(echo "${row}" | jq -r '.value' | base64 --decode)
  env_args+=(-e)
  env_args+=("${key}=${decoded}")
done

docker build . -t bob

docker rm bob || true

docker run \
  "${env_args[@]}" \
  -e BOB_WHO="agent" \
  -e BOB_LOCAL_JOBS="BuildDockerElixir,BuildDockerErlang,BuildElixirGuides,BuildElixir,BuildHexDocs,BuildOTP,Clean" \
  -e BOB_REMOTE_JOBS="BuildDockerElixir,BuildDockerErlang,BuildElixirGuides,BuildElixir,BuildHexDocs,BuildOTP" \
  -e BOB_PARALLEL_JOBS="10" \
  -e RELEASE_NODE="bob@127.0.0.1" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(pwd)/tmp:/tmp \
  --name bob \
  bob /app/bin/bob start
